import type { Section, Template, ValidationConfig } from "../../../types/type";
import type { AllBankBalance } from "../../../types/cashType";
const sections: Section<AllBankBalance>[] = [
  {
    title: "Basic Information",
    fields: [
      {
        key: "account_no",
        label: "Account Number",
        type: "text",
        oldValue: "old_account_no",
      },
      {
        key: "bank_name",
        label: "Bank Name",
        type: "text",
        oldValue: "old_bank_name",
      },
      {
        key: "iban",
        label: "IBAN",
        type: "text",
        oldValue: "old_iban",
      },
      {
        key: "currency_code",
        label: "Currency",
        type: "text",
        oldValue: "old_currency_code",
      },
      {
        key: "balance_type",
        label: "Balance Type",
        type: "select",
        options: [
          { value: "CURRENT", label: "Current" },
          { value: "SAVINGS", label: "Savings" },
          { value: "LOAN", label: "Loan" },
          { value: "OTHERS", label: "Others" },
        ],
        oldValue: "old_balance_type",
      },
      {
        key: "country",
        label: "Country",
        type: "text",
      },
      {
        key: "nickname",
        label: "Nickname",
        type: "text",
        oldValue: "old_nickname",
      },
      {
        key: "as_of_date",
        label: "As of Date",
        type: "date",
        oldValue: "old_as_of_date",
      },
      {
        key: "as_of_time",
        label: "As of Time",
        type: "time",
        oldValue: "old_as_of_time",
      },
    ],
    editableKeys: [
      "account_no",
      "bank_name",
      "iban",
      "currency_code",
      "balance_type",
      "country",
      "nickname",
      "as_of_date",
      "as_of_time",
    ],
  },
  {
    title: "Balances",
    fields: [
      {
        key: "opening_balance",
        label: "Opening Balance",
        type: "number",
        oldValue: "old_opening_balance",
      },
      {
        key: "closing_balance",
        label: "Closing Balance",
        type: "number",
        oldValue: "old_closing_balance",
      },
      {
        key: "balance_amount",
        label: "Balance Amount",
        type: "number",
        oldValue: "old_balance_amount",
      },
      {
        key: "total_credits",
        label: "Total Credits",
        type: "number",
        oldValue: "old_total_credits",
      },
      {
        key: "total_debits",
        label: "Total Debits",
        type: "number",
        oldValue: "old_total_debits",
      },
    ],
    editableKeys: [
      "opening_balance",
      "closing_balance",
      "balance_amount",
      "total_credits",
      "total_debits",
    ],
  },
  {
    title: "Transaction Metadata",
    fields: [
      {
        key: "source_channel",
        label: "Source Channel",
        type: "text",
        oldValue: "old_source_channel",
      },
      {
        key: "statement_type",
        label: "Statement Type",
        type: "text",
        oldValue: "old_statement_type",
      },
      {
        key: "processing_status",
        label: "Processing Status",
        type: "text",
      },
      {
        key: "reason",
        label: "Reason",
        type: "text",
      },
    ],
    editableKeys: [
      "source_channel",
      "statement_type",
      "processing_status",
      "reason",
    ],
  },
  {
    title: "Audit Metadata",
    fields: [
      { key: "balance_id", label: "Balance ID", type: "text" },
      { key: "action_id", label: "Action ID", type: "text" },
      { key: "action_type", label: "Action Type", type: "text" },
      { key: "checker_at", label: "Checked At", type: "date" },
      { key: "checker_by", label: "Checked By", type: "text" },
      { key: "checker_comment", label: "Checker Comment", type: "text" },
      { key: "created_by", label: "Created By", type: "text" },
      { key: "created_at", label: "Created At", type: "date" },
      { key: "edited_by", label: "Edited By", type: "text" },
      { key: "edited_at", label: "Edited At", type: "date" },
      { key: "deleted_by", label: "Deleted By", type: "text" },
      { key: "deleted_at", label: "Deleted At", type: "date" },
    ],
  },
];

const bankBalanceValidationConfig: ValidationConfig = {
  requiredHeaders: [
    "bank_name",
    "account_no",
    "iban",
    "currency_code",
    "nickname",
    "country",
    "as_of_date",
    "as_of_time",
    "balance_type",
    "balance_amount",
    "statement_type",
    "source_channel",
    "opening_balance",
    "total_credits",
    "total_debits",
    "closing_balance",
  ],
  requiredFields: [
    "bank_name",
    "account_no",
    "iban",
    "currency_code",
    // "nickname",
    // "country",
    "as_of_date",
    "as_of_time",
    "balance_type",
    "balance_amount",
    "statement_type",
    "source_channel",
    // "opening_balance",
    // "total_credits",
    // "total_debits",
    // "closing_balance",
  ],
  numericFields: [
    "balance_amount",
    "opening_balance",
    "total_credits",
    "total_debits",
    "closing_balance",
  ],
};

const templates: Template[] = [
  {
    id: "bank_balance",
    name: "Bank Balance Template",
    type: "Excel",
    description: "Template for capturing bank balance details",
    headers: [
      "bank_name",
      "account_no",
      "iban",
      "currency_code",
      "nickname",
      "country",
      "as_of_date",
      "as_of_time",
      "balance_type",
      "balance_amount",
      "statement_type",
      "source_channel",
      "opening_balance",
      "total_credits",
      "total_debits",
      "closing_balance",
    ],
    sampleRow: [
      "HDFC Bank",
      "1234567890",
      "IN91HDFC00012345678900",
      "INR",
      "Main Current Account",
      "India",
      "2025-09-15",
      "14:30:00",
      "CURRENT",
      "1500000.00",
      "DAILY",
      "MANUAL",
      "1000000.00",
      "600000.00",
      "100000.00",
      "1500000.00",
    ],

 
  },
];

export { templates, bankBalanceValidationConfig, sections };
