/**
 * @description
 * This file contains a constant array of currency objects.
 * Each object includes the currency code, name, country of origin, and symbol.
 * This data is intended to be used for auto-populating form fields based on user input.
 *
 * @interface Currency
 * @property {string} currencyCode - The ISO 4217 alphabetic code for the currency.
 * @property {string} currencyName - The official name of the currency.
 * @property {string} country - The country or entity that uses the currency.
 * @property {string} symbol - The graphical symbol for the currency.
 */
export interface Currency {
  currencyCode: string;
  currencyName: string;
  country: string;
  symbol: string;
}

export const CURRENCY_DATA: Currency[] = [
  { country: 'AFGHANISTAN', currencyName: 'Afghani', currencyCode: 'AFN', symbol: '؋' },
  { country: 'ÅLAND ISLANDS', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'ALBANIA', currencyName: 'Lek', currencyCode: 'ALL', symbol: 'L' },
  { country: 'ALGERIA', currencyName: 'Algerian Dinar', currencyCode: 'DZD', symbol: 'د.ج' },
  { country: 'AMERICAN SAMOA', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'ANDORRA', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'ANGOLA', currencyName: 'Kwanza', currencyCode: 'AOA', symbol: 'Kz' },
  { country: 'ANGUILLA', currencyName: 'East Caribbean Dollar', currencyCode: 'XCD', symbol: '$' },
  { country: 'ANTIGUA AND BARBUDA', currencyName: 'East Caribbean Dollar', currencyCode: 'XCD', symbol: '$' },
  { country: 'ARGENTINA', currencyName: 'Argentine Peso', currencyCode: 'ARS', symbol: '$' },
  { country: 'ARMENIA', currencyName: 'Armenian Dram', currencyCode: 'AMD', symbol: '֏' },
  { country: 'ARUBA', currencyName: 'Aruban Florin', currencyCode: 'AWG', symbol: 'ƒ' },
  { country: 'AUSTRALIA', currencyName: 'Australian Dollar', currencyCode: 'AUD', symbol: '$' },
  { country: 'AUSTRIA', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'AZERBAIJAN', currencyName: 'Azerbaijan Manat', currencyCode: 'AZN', symbol: '₼' },
  { country: 'BAHAMAS (THE)', currencyName: 'Bahamian Dollar', currencyCode: 'BSD', symbol: '$' },
  { country: 'BAHRAIN', currencyName: 'Bahraini Dinar', currencyCode: 'BHD', symbol: '.د.ب' },
  { country: 'BANGLADESH', currencyName: 'Taka', currencyCode: 'BDT', symbol: '৳' },
  { country: 'BARBADOS', currencyName: 'Barbados Dollar', currencyCode: 'BBD', symbol: '$' },
  { country: 'BELARUS', currencyName: 'Belarusian Ruble', currencyCode: 'BYN', symbol: 'Br' },
  { country: 'BELGIUM', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'BELIZE', currencyName: 'Belize Dollar', currencyCode: 'BZD', symbol: 'BZ$' },
  { country: 'BENIN', currencyName: 'CFA Franc BCEAO', currencyCode: 'XOF', symbol: 'CFA' },
  { country: 'BERMUDA', currencyName: 'Bermudian Dollar', currencyCode: 'BMD', symbol: '$' },
  { country: 'BHUTAN', currencyName: 'Ngultrum', currencyCode: 'BTN', symbol: 'Nu.' },
  { country: 'BOLIVIA (PLURINATIONAL STATE OF)', currencyName: 'Boliviano', currencyCode: 'BOB', symbol: 'Bs.' },
  { country: 'BONAIRE, SINT EUSTATIUS AND SABA', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'BOSNIA AND HERZEGOVINA', currencyName: 'Convertible Mark', currencyCode: 'BAM', symbol: 'KM' },
  { country: 'BOTSWANA', currencyName: 'Pula', currencyCode: 'BWP', symbol: 'P' },
  { country: 'BRAZIL', currencyName: 'Brazilian Real', currencyCode: 'BRL', symbol: 'R$' },
  { country: 'BRITISH INDIAN OCEAN TERRITORY (THE)', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'BRUNEI DARUSSALAM', currencyName: 'Brunei Dollar', currencyCode: 'BND', symbol: '$' },
  { country: 'BULGARIA', currencyName: 'Bulgarian Lev', currencyCode: 'BGN', symbol: 'лв' },
  { country: 'BURKINA FASO', currencyName: 'CFA Franc BCEAO', currencyCode: 'XOF', symbol: 'CFA' },
  { country: 'BURUNDI', currencyName: 'Burundi Franc', currencyCode: 'BIF', symbol: 'FBu' },
  { country: 'CABO VERDE', currencyName: 'Cabo Verde Escudo', currencyCode: 'CVE', symbol: 'Esc' },
  { country: 'CAMBODIA', currencyName: 'Riel', currencyCode: 'KHR', symbol: '៛' },
  { country: 'CAMEROON', currencyName: 'CFA Franc BEAC', currencyCode: 'XAF', symbol: 'FCFA' },
  { country: 'CANADA', currencyName: 'Canadian Dollar', currencyCode: 'CAD', symbol: '$' },
  { country: 'CAYMAN ISLANDS (THE)', currencyName: 'Cayman Islands Dollar', currencyCode: 'KYD', symbol: '$' },
  { country: 'CENTRAL AFRICAN REPUBLIC (THE)', currencyName: 'CFA Franc BEAC', currencyCode: 'XAF', symbol: 'FCFA' },
  { country: 'CHAD', currencyName: 'CFA Franc BEAC', currencyCode: 'XAF', symbol: 'FCFA' },
  { country: 'CHILE', currencyName: 'Chilean Peso', currencyCode: 'CLP', symbol: '$' },
  { country: 'CHINA', currencyName: 'Yuan Renminbi', currencyCode: 'CNY', symbol: '¥' },
  { country: 'COLOMBIA', currencyName: 'Colombian Peso', currencyCode: 'COP', symbol: '$' },
  { country: 'COMOROS (THE)', currencyName: 'Comorian Franc ', currencyCode: 'KMF', symbol: 'CF' },
  { country: 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)', currencyName: 'Congolese Franc', currencyCode: 'CDF', symbol: 'FC' },
  { country: 'CONGO (THE)', currencyName: 'CFA Franc BEAC', currencyCode: 'XAF', symbol: 'FCFA' },
  { country: 'COOK ISLANDS (THE)', currencyName: 'New Zealand Dollar', currencyCode: 'NZD', symbol: '$' },
  { country: 'COSTA RICA', currencyName: 'Costa Rican Colon', currencyCode: 'CRC', symbol: '₡' },
  { country: 'CÔTE D\'IVOIRE', currencyName: 'CFA Franc BCEAO', currencyCode: 'XOF', symbol: 'CFA' },
  { country: 'CROATIA', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'CUBA', currencyName: 'Cuban Peso', currencyCode: 'CUP', symbol: '₱' },
  { country: 'CURAÇAO', currencyName: 'Netherlands Antillean Guilder', currencyCode: 'ANG', symbol: 'ƒ' },
  { country: 'CYPRUS', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'CZECHIA', currencyName: 'Czech Koruna', currencyCode: 'CZK', symbol: 'Kč' },
  { country: 'DENMARK', currencyName: 'Danish Krone', currencyCode: 'DKK', symbol: 'kr' },
  { country: 'DJIBOUTI', currencyName: 'Djibouti Franc', currencyCode: 'DJF', symbol: 'Fdj' },
  { country: 'DOMINICA', currencyName: 'East Caribbean Dollar', currencyCode: 'XCD', symbol: '$' },
  { country: 'DOMINICAN REPUBLIC (THE)', currencyName: 'Dominican Peso', currencyCode: 'DOP', symbol: 'RD$' },
  { country: 'ECUADOR', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'EGYPT', currencyName: 'Egyptian Pound', currencyCode: 'EGP', symbol: 'E£' },
  { country: 'EL SALVADOR', currencyName: 'El Salvador Colon', currencyCode: 'SVC', symbol: '₡' },
  { country: 'EQUATORIAL GUINEA', currencyName: 'CFA Franc BEAC', currencyCode: 'XAF', symbol: 'FCFA' },
  { country: 'ERITREA', currencyName: 'Nakfa', currencyCode: 'ERN', symbol: 'Nfk' },
  { country: 'ESTONIA', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'ESWATINI', currencyName: 'Lilangeni', currencyCode: 'SZL', symbol: 'L' },
  { country: 'ETHIOPIA', currencyName: 'Ethiopian Birr', currencyCode: 'ETB', symbol: 'Br' },
  { country: 'EUROPEAN UNION', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'FALKLAND ISLANDS (THE) [MALVINAS]', currencyName: 'Falkland Islands Pound', currencyCode: 'FKP', symbol: '£' },
  { country: 'FAROE ISLANDS (THE)', currencyName: 'Danish Krone', currencyCode: 'DKK', symbol: 'kr' },
  { country: 'FIJI', currencyName: 'Fiji Dollar', currencyCode: 'FJD', symbol: '$' },
  { country: 'FINLAND', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'FRANCE', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'FRENCH GUIANA', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'FRENCH POLYNESIA', currencyName: 'CFP Franc', currencyCode: 'XPF', symbol: '₣' },
  { country: 'GABON', currencyName: 'CFA Franc BEAC', currencyCode: 'XAF', symbol: 'FCFA' },
  { country: 'GAMBIA (THE)', currencyName: 'Dalasi', currencyCode: 'GMD', symbol: 'D' },
  { country: 'GEORGIA', currencyName: 'Lari', currencyCode: 'GEL', symbol: '₾' },
  { country: 'GERMANY', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'GHANA', currencyName: 'Ghana Cedi', currencyCode: 'GHS', symbol: '₵' },
  { country: 'GIBRALTAR', currencyName: 'Gibraltar Pound', currencyCode: 'GIP', symbol: '£' },
  { country: 'GREECE', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'GREENLAND', currencyName: 'Danish Krone', currencyCode: 'DKK', symbol: 'kr' },
  { country: 'GRENADA', currencyName: 'East Caribbean Dollar', currencyCode: 'XCD', symbol: '$' },
  { country: 'GUADELOUPE', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'GUAM', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'GUATEMALA', currencyName: 'Quetzal', currencyCode: 'GTQ', symbol: 'Q' },
  { country: 'GUERNSEY', currencyName: 'Pound Sterling', currencyCode: 'GBP', symbol: '£' },
  { country: 'GUINEA', currencyName: 'Guinean Franc', currencyCode: 'GNF', symbol: 'FG' },
  { country: 'GUINEA-BISSAU', currencyName: 'CFA Franc BCEAO', currencyCode: 'XOF', symbol: 'CFA' },
  { country: 'GUYANA', currencyName: 'Guyana Dollar', currencyCode: 'GYD', symbol: '$' },
  { country: 'HAITI', currencyName: 'Gourde', currencyCode: 'HTG', symbol: 'G' },
  { country: 'HONDURAS', currencyName: 'Lempira', currencyCode: 'HNL', symbol: 'L' },
  { country: 'HONG KONG', currencyName: 'Hong Kong Dollar', currencyCode: 'HKD', symbol: '$' },
  { country: 'HUNGARY', currencyName: 'Forint', currencyCode: 'HUF', symbol: 'Ft' },
  { country: 'ICELAND', currencyName: 'Iceland Krona', currencyCode: 'ISK', symbol: 'kr' },
  { country: 'INDIA', currencyName: 'Indian Rupee', currencyCode: 'INR', symbol: '₹' },
  { country: 'INDONESIA', currencyName: 'Rupiah', currencyCode: 'IDR', symbol: 'Rp' },
  { country: 'IRAN (ISLAMIC REPUBLIC OF)', currencyName: 'Iranian Rial', currencyCode: 'IRR', symbol: '﷼' },
  { country: 'IRAQ', currencyName: 'Iraqi Dinar', currencyCode: 'IQD', symbol: 'ع.د' },
  { country: 'IRELAND', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'ISLE OF MAN', currencyName: 'Pound Sterling', currencyCode: 'GBP', symbol: '£' },
  { country: 'ISRAEL', currencyName: 'New Israeli Sheqel', currencyCode: 'ILS', symbol: '₪' },
  { country: 'ITALY', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'JAMAICA', currencyName: 'Jamaican Dollar', currencyCode: 'JMD', symbol: 'J$' },
  { country: 'JAPAN', currencyName: 'Yen', currencyCode: 'JPY', symbol: '¥' },
  { country: 'JERSEY', currencyName: 'Pound Sterling', currencyCode: 'GBP', symbol: '£' },
  { country: 'JORDAN', currencyName: 'Jordanian Dinar', currencyCode: 'JOD', symbol: 'JD' },
  { country: 'KAZAKHSTAN', currencyName: 'Tenge', currencyCode: 'KZT', symbol: '₸' },
  { country: 'KENYA', currencyName: 'Kenyan Shilling', currencyCode: 'KES', symbol: 'KSh' },
  { country: 'KIRIBATI', currencyName: 'Australian Dollar', currencyCode: 'AUD', symbol: '$' },
  { country: 'KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)', currencyName: 'North Korean Won', currencyCode: 'KPW', symbol: '₩' },
  { country: 'KOREA (THE REPUBLIC OF)', currencyName: 'Won', currencyCode: 'KRW', symbol: '₩' },
  { country: 'KUWAIT', currencyName: 'Kuwaiti Dinar', currencyCode: 'KWD', symbol: 'د.ك' },
  { country: 'KYRGYZSTAN', currencyName: 'Som', currencyCode: 'KGS', symbol: 'с' },
  { country: 'LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)', currencyName: 'Lao Kip', currencyCode: 'LAK', symbol: '₭' },
  { country: 'LATVIA', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'LEBANON', currencyName: 'Lebanese Pound', currencyCode: 'LBP', symbol: 'ل.ل' },
  { country: 'LESOTHO', currencyName: 'Loti', currencyCode: 'LSL', symbol: 'L' },
  { country: 'LIBERIA', currencyName: 'Liberian Dollar', currencyCode: 'LRD', symbol: '$' },
  { country: 'LIBYA', currencyName: 'Libyan Dinar', currencyCode: 'LYD', symbol: 'ل.د' },
  { country: 'LIECHTENSTEIN', currencyName: 'Swiss Franc', currencyCode: 'CHF', symbol: 'CHF' },
  { country: 'LITHUANIA', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'LUXEMBOURG', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'MACAO', currencyName: 'Pataca', currencyCode: 'MOP', symbol: 'MOP$' },
  { country: 'MADAGASCAR', currencyName: 'Malagasy Ariary', currencyCode: 'MGA', symbol: 'Ar' },
  { country: 'MALAWI', currencyName: 'Malawi Kwacha', currencyCode: 'MWK', symbol: 'MK' },
  { country: 'MALAYSIA', currencyName: 'Malaysian Ringgit', currencyCode: 'MYR', symbol: 'RM' },
  { country: 'MALDIVES', currencyName: 'Rufiyaa', currencyCode: 'MVR', symbol: 'Rf' },
  { country: 'MALI', currencyName: 'CFA Franc BCEAO', currencyCode: 'XOF', symbol: 'CFA' },
  { country: 'MALTA', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'MARSHALL ISLANDS (THE)', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'MARTINIQUE', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'MAURITANIA', currencyName: 'Ouguiya', currencyCode: 'MRU', symbol: 'UM' },
  { country: 'MAURITIUS', currencyName: 'Mauritius Rupee', currencyCode: 'MUR', symbol: '₨' },
  { country: 'MAYOTTE', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'MEXICO', currencyName: 'Mexican Peso', currencyCode: 'MXN', symbol: '$' },
  { country: 'MICRONESIA (FEDERATED STATES OF)', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'MOLDOVA (THE REPUBLIC OF)', currencyName: 'Moldovan Leu', currencyCode: 'MDL', symbol: 'L' },
  { country: 'MONACO', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'MONGOLIA', currencyName: 'Tugrik', currencyCode: 'MNT', symbol: '₮' },
  { country: 'MONTENEGRO', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'MONTSERRAT', currencyName: 'East Caribbean Dollar', currencyCode: 'XCD', symbol: '$' },
  { country: 'MOROCCO', currencyName: 'Moroccan Dirham', currencyCode: 'MAD', symbol: 'د.م.' },
  { country: 'MOZAMBIQUE', currencyName: 'Mozambique Metical', currencyCode: 'MZN', symbol: 'MT' },
  { country: 'MYANMAR', currencyName: 'Kyat', currencyCode: 'MMK', symbol: 'K' },
  { country: 'NAMIBIA', currencyName: 'Namibia Dollar', currencyCode: 'NAD', symbol: '$' },
  { country: 'NAURU', currencyName: 'Australian Dollar', currencyCode: 'AUD', symbol: '$' },
  { country: 'NEPAL', currencyName: 'Nepalese Rupee', currencyCode: 'NPR', symbol: '₨' },
  { country: 'NETHERLANDS (THE)', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'NEW CALEDONIA', currencyName: 'CFP Franc', currencyCode: 'XPF', symbol: '₣' },
  { country: 'NEW ZEALAND', currencyName: 'New Zealand Dollar', currencyCode: 'NZD', symbol: '$' },
  { country: 'NICARAGUA', currencyName: 'Cordoba Oro', currencyCode: 'NIO', symbol: 'C$' },
  { country: 'NIGER (THE)', currencyName: 'CFA Franc BCEAO', currencyCode: 'XOF', symbol: 'CFA' },
  { country: 'NIGERIA', currencyName: 'Naira', currencyCode: 'NGN', symbol: '₦' },
  { country: 'NIUE', currencyName: 'New Zealand Dollar', currencyCode: 'NZD', symbol: '$' },
  { country: 'NORFOLK ISLAND', currencyName: 'Australian Dollar', currencyCode: 'AUD', symbol: '$' },
  { country: 'NORTHERN MARIANA ISLANDS (THE)', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'NORTH MACEDONIA', currencyName: 'Denar', currencyCode: 'MKD', symbol: 'ден' },
  { country: 'NORWAY', currencyName: 'Norwegian Krone', currencyCode: 'NOK', symbol: 'kr' },
  { country: 'OMAN', currencyName: 'Rial Omani', currencyCode: 'OMR', symbol: '﷼' },
  { country: 'PAKISTAN', currencyName: 'Pakistan Rupee', currencyCode: 'PKR', symbol: '₨' },
  { country: 'PALAU', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'PANAMA', currencyName: 'Balboa', currencyCode: 'PAB', symbol: 'B/.' },
  { country: 'PAPUA NEW GUINEA', currencyName: 'Kina', currencyCode: 'PGK', symbol: 'K' },
  { country: 'PARAGUAY', currencyName: 'Guarani', currencyCode: 'PYG', symbol: '₲' },
  { country: 'PERU', currencyName: 'Sol', currencyCode: 'PEN', symbol: 'S/' },
  { country: 'PHILIPPINES (THE)', currencyName: 'Philippine Peso', currencyCode: 'PHP', symbol: '₱' },
  { country: 'PITCAIRN', currencyName: 'New Zealand Dollar', currencyCode: 'NZD', symbol: '$' },
  { country: 'POLAND', currencyName: 'Zloty', currencyCode: 'PLN', symbol: 'zł' },
  { country: 'PORTUGAL', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'PUERTO RICO', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'QATAR', currencyName: 'Qatari Rial', currencyCode: 'QAR', symbol: '﷼' },
  { country: 'RÉUNION', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'ROMANIA', currencyName: 'Romanian Leu', currencyCode: 'RON', symbol: 'lei' },
  { country: 'RUSSIAN FEDERATION (THE)', currencyName: 'Russian Ruble', currencyCode: 'RUB', symbol: '₽' },
  { country: 'RWANDA', currencyName: 'Rwanda Franc', currencyCode: 'RWF', symbol: 'R₣' },
  { country: 'SAINT BARTHÉLEMY', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', currencyName: 'Saint Helena Pound', currencyCode: 'SHP', symbol: '£' },
  { country: 'SAINT KITTS AND NEVIS', currencyName: 'East Caribbean Dollar', currencyCode: 'XCD', symbol: '$' },
  { country: 'SAINT LUCIA', currencyName: 'East Caribbean Dollar', currencyCode: 'XCD', symbol: '$' },
  { country: 'SAINT MARTIN (FRENCH PART)', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'SAINT PIERRE AND MIQUELON', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'SAINT VINCENT AND THE GRENADINES', currencyName: 'East Caribbean Dollar', currencyCode: 'XCD', symbol: '$' },
  { country: 'SAMOA', currencyName: 'Tala', currencyCode: 'WST', symbol: 'WS$' },
  { country: 'SAN MARINO', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'SAO TOME AND PRINCIPE', currencyName: 'Dobra', currencyCode: 'STN', symbol: 'Db' },
  { country: 'SAUDI ARABIA', currencyName: 'Saudi Riyal', currencyCode: 'SAR', symbol: '﷼' },
  { country: 'SENEGAL', currencyName: 'CFA Franc BCEAO', currencyCode: 'XOF', symbol: 'CFA' },
  { country: 'SERBIA', currencyName: 'Serbian Dinar', currencyCode: 'RSD', symbol: 'дин.' },
  { country: 'SEYCHELLES', currencyName: 'Seychelles Rupee', currencyCode: 'SCR', symbol: '₨' },
  { country: 'SIERRA LEONE', currencyName: 'Leone', currencyCode: 'SLL', symbol: 'Le' },
  { country: 'SINGAPORE', currencyName: 'Singapore Dollar', currencyCode: 'SGD', symbol: '$' },
  { country: 'SINT MAARTEN (DUTCH PART)', currencyName: 'Netherlands Antillean Guilder', currencyCode: 'ANG', symbol: 'ƒ' },
  { country: 'SLOVAKIA', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'SLOVENIA', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'SOLOMON ISLANDS', currencyName: 'Solomon Islands Dollar', currencyCode: 'SBD', symbol: '$' },
  { country: 'SOMALIA', currencyName: 'Somali Shilling', currencyCode: 'SOS', symbol: 'S' },
  { country: 'SOUTH AFRICA', currencyName: 'Rand', currencyCode: 'ZAR', symbol: 'R' },
  { country: 'SOUTH SUDAN', currencyName: 'South Sudanese Pound', currencyCode: 'SSP', symbol: '£' },
  { country: 'SPAIN', currencyName: 'Euro', currencyCode: 'EUR', symbol: '€' },
  { country: 'SRI LANKA', currencyName: 'Sri Lanka Rupee', currencyCode: 'LKR', symbol: '₨' },
  { country: 'SUDAN (THE)', currencyName: 'Sudanese Pound', currencyCode: 'SDG', symbol: 'ج.س.' },
  { country: 'SURINAME', currencyName: 'Surinam Dollar', currencyCode: 'SRD', symbol: '$' },
  { country: 'SVALBARD AND JAN MAYEN', currencyName: 'Norwegian Krone', currencyCode: 'NOK', symbol: 'kr' },
  { country: 'SWEDEN', currencyName: 'Swedish Krona', currencyCode: 'SEK', symbol: 'kr' },
  { country: 'SWITZERLAND', currencyName: 'Swiss Franc', currencyCode: 'CHF', symbol: 'CHF' },
  { country: 'SYRIAN ARAB REPUBLIC', currencyName: 'Syrian Pound', currencyCode: 'SYP', symbol: '£S' },
  { country: 'TAIWAN (PROVINCE OF CHINA)', currencyName: 'New Taiwan Dollar', currencyCode: 'TWD', symbol: 'NT$' },
  { country: 'TAJIKISTAN', currencyName: 'Somoni', currencyCode: 'TJS', symbol: 'SM' },
  { country: 'TANZANIA, UNITED REPUBLIC OF', currencyName: 'Tanzanian Shilling', currencyCode: 'TZS', symbol: 'TSh' },
  { country: 'THAILAND', currencyName: 'Baht', currencyCode: 'THB', symbol: '฿' },
  { country: 'TIMOR-LESTE', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'TOGO', currencyName: 'CFA Franc BCEAO', currencyCode: 'XOF', symbol: 'CFA' },
  { country: 'TOKELAU', currencyName: 'New Zealand Dollar', currencyCode: 'NZD', symbol: '$' },
  { country: 'TONGA', currencyName: 'Pa’anga', currencyCode: 'TOP', symbol: 'T$' },
  { country: 'TRINIDAD AND TOBAGO', currencyName: 'Trinidad and Tobago Dollar', currencyCode: 'TTD', symbol: 'TT$' },
  { country: 'TUNISIA', currencyName: 'Tunisian Dinar', currencyCode: 'TND', symbol: 'د.ت' },
  { country: 'TURKEY', currencyName: 'Turkish Lira', currencyCode: 'TRY', symbol: '₺' },
  { country: 'TURKMENISTAN', currencyName: 'Turkmenistan New Manat', currencyCode: 'TMT', symbol: 'T' },
  { country: 'TURKS AND CAICOS ISLANDS (THE)', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'TUVALU', currencyName: 'Australian Dollar', currencyCode: 'AUD', symbol: '$' },
  { country: 'UGANDA', currencyName: 'Uganda Shilling', currencyCode: 'UGX', symbol: 'USh' },
  { country: 'UKRAINE', currencyName: 'Hryvnia', currencyCode: 'UAH', symbol: '₴' },
  { country: 'UNITED ARAB EMIRATES (THE)', currencyName: 'UAE Dirham', currencyCode: 'AED', symbol: 'د.إ' },
  { country: 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)', currencyName: 'Pound Sterling', currencyCode: 'GBP', symbol: '£' },
  { country: 'UNITED STATES OF AMERICA (THE)', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'URUGUAY', currencyName: 'Peso Uruguayo', currencyCode: 'UYU', symbol: '$U' },
  { country: 'UZBEKISTAN', currencyName: 'Uzbekistan Sum', currencyCode: 'UZS', symbol: 'soʻm' },
  { country: 'VANUATU', currencyName: 'Vatu', currencyCode: 'VUV', symbol: 'VT' },
  { country: 'VENEZUELA (BOLIVARIAN REPUBLIC OF)', currencyName: 'Bolívar Soberano', currencyCode: 'VES', symbol: 'Bs.' },
  { country: 'VIET NAM', currencyName: 'Dong', currencyCode: 'VND', symbol: '₫' },
  { country: 'VIRGIN ISLANDS (BRITISH)', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'VIRGIN ISLANDS (U.S.)', currencyName: 'US Dollar', currencyCode: 'USD', symbol: '$' },
  { country: 'WALLIS AND FUTUNA', currencyName: 'CFP Franc', currencyCode: 'XPF', symbol: '₣' },
  { country: 'WESTERN SAHARA', currencyName: 'Moroccan Dirham', currencyCode: 'MAD', symbol: 'د.م.' },
  { country: 'YEMEN', currencyName: 'Yemeni Rial', currencyCode: 'YER', symbol: '﷼' },
  { country: 'ZAMBIA', currencyName: 'Zambian Kwacha', currencyCode: 'ZMW', symbol: 'ZK' },
  { country: 'ZIMBABWE', currencyName: 'Zimbabwe Dollar', currencyCode: 'ZWL', symbol: 'Z$' }
];
